rvm:
  - 1.8.7
  - 1.9.2
  - ree
  - rbx-2.0

script: "bundle exec rake clean test cucumber"

gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails3_1.gemfile
env: "AWS_ACCESS_KEY_ID=AKIAI2Q4BG4ALE7GOTIA AWS_SECRET_ACCESS_KEY=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 PAPERCLIP_TEST_BUCKET=paperclip-travis"
